spring.application.name=api-gateway
server.port=8765

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Disable Spring Cloud compatibility check
spring.cloud.compatibility-verifier.enabled=false

# Observability
management.endpoints.web.exposure.include=health,info,metrics,gateway
management.tracing.sampling.probability=1.0

# Global CORS Configuration for Gateway
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
