spring.application.name=naming-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable Spring Cloud compatibility check for Spring Boot 3.5.x / Java 24
spring.cloud.compatibility-verifier.enabled=false

management.endpoints.web.exposure.include=health,info,metrics
