spring.application.name=config-server
server.port=8888

# Use native file-based configuration profile
spring.profiles.active=native
spring.cloud.config.server.native.search-locations=classpath:/config

eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Disable Spring Cloud compatibility check
spring.cloud.compatibility-verifier.enabled=false

management.endpoints.web.exposure.include=health,info,metrics
